# Generated by Django 5.0.6 on 2024-05-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipdetail',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='ship.ship'),
        ),
    ]
