# Generated by Django 5.0.6 on 2024-05-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='quantity',
        ),
    ]
