# Generated by Django 5.0.1 on 2024-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='productId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
